# Generated by Django 5.2.5 on 2025-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default='Dhaka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(default='no email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Regular Employee', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='telephone_number',
            field=models.CharField(default='No Phone', max_length=15),
            preserve_default=False,
        ),
    ]
